_MFW_MESSAGE("sad file needs to be reworked")

#if MFW_CONFIGURATION_IS(DEBUG)
	#define _HAS_EXCEPTIONS 1
	#define _ITERATOR_DEBUG_LEVEL 2
	#define _HAS_ITERATOR_DEBUGGING 1
	#define _CONTAINER_DEBUG_LEVEL 1
	#define _SECURE_SCL 1
	#define _ENABLE_STL_INTERNAL_CHECK
	#define _CRTDBG_MAP_ALLOC
	#define _SYSCRT_DEBUG
	#define _SECURE_SCL_THROWS 1

	#define _FORTIFY_SOURCE 2

	#define __BIONIC_FORTIFY
	#define __BIONIC_DECLARE_FORTIFY_HELPERS
#elif MFW_CONFIGURATION_IS(RELEASE)
	#define _HAS_EXCEPTIONS 0
	#define _ITERATOR_DEBUG_LEVEL 0
	#define _HAS_ITERATOR_DEBUGGING 0
	#define _CONTAINER_DEBUG_LEVEL 0
	#define _SECURE_SCL 0
	#define _SECURE_SCL_THROWS 0

	#define _FORTIFY_SOURCE 0
#else
	#error
#endif

#define _SECURE_SCL_DEPRECATE 1
#define _ALLOW_RTCc_IN_STL

#ifndef _GNU_SOURCE
	#define _GNU_SOURCE
#endif
#define _ISOC99_SOURCE
#define _ISOC11_SOURCE
#define _ISOC2X_SOURCE
#define _POSIX_SOURCE
#define _XOPEN_SOURCE
#define _XOPEN_SOURCE_EXTENDED
#define _LARGEFILE_SOURCE
#define _LARGEFILE64_SOURCE
#define _ATFILE_SOURCE
#define __STDC_WANT_LIB_EXT2__ 1
#define __STDC_WANT_IEC_60559_TYPES_EXT__
#define __STDC_WANT_IEC_60559_BFP_EXT__
#define __STDC_WANT_IEC_60559_FUNCS_EXT__

#define _BSD_SOURCE

#define ANDROID_STRICT