#define MFW_BUILD_EXECUTABLE_FLAG _MFW_BIT(0)
#define MFW_BUILD_STATIC_FLAG _MFW_BIT(1)
#define MFW_BUILD_SHARED_FLAG _MFW_BIT(2)
#define _MFW_BUILD_FLAGS_LAST_BIT 2
#define MFW_BUILD_EMBEDDED (MFW_BUILD_STATIC_FLAG|_MFW_BIT(_MFW_BUILD_FLAGS_LAST_BIT+1))
#define MFW_BUILD_STATIC (MFW_BUILD_STATIC_FLAG|_MFW_BIT(_MFW_BUILD_FLAGS_LAST_BIT+2))
#define MFW_BUILD_SHARED (MFW_BUILD_SHARED_FLAG|_MFW_BIT(_MFW_BUILD_FLAGS_LAST_BIT+3))
#define MFW_BUILD_EXECUTABLE (MFW_BUILD_SHARED_FLAG|MFW_BUILD_EXECUTABLE_FLAG|_MFW_BIT(_MFW_BUILD_FLAGS_LAST_BIT+4))
#if MFW_OS_IS(WINDOWS)
	#define MFW_BUILD_EXECUTABLE_WINDOWS (MFW_BUILD_SHARED_FLAG|MFW_BUILD_EXECUTABLE_FLAG|_MFW_BIT(_MFW_BUILD_FLAGS_LAST_BIT+5))
#endif

#define MFW_BUILD_FLAGGED(what) (MFW_BUILD & MFW_BUILD_##what##_FLAG)
#define MFW_BUILD_IS(what) (MFW_BUILD == MFW_BUILD_##what)
#define MFW_IS_BUIDLING(what) (defined(MFW_BUILDING_##what))
//#define MFW_BUILD_FLAGGED(name, what) (MFW_##name##_BUILD & MFW_BUILD_##what##_FLAG)
//#define MFW_BUILD_IS(name, what) (MFW_##name##_BUILD == MFW_BUILD_##what)

#if defined _LIB || \
	defined LIB
	#define MFW_BUILD MFW_BUILD_STATIC
#elif defined _SHARED || \
		defined SHARED
	#define MFW_BUILD MFW_BUILD_SHARED
#elif defined _CONSOLE || \
		defined CONSOLE
	#define MFW_BUILD MFW_BUILD_EXECUTABLE
#endif
#if MFW_OS_IS(WINDOWS) && !defined MFW_BUILD
	#if defined _WINDLL || \
		defined WINDLL || \
		defined _USRDLL || \
		defined USRDLL
		#define MFW_BUILD MFW_BUILD_SHARED
	#elif defined _WINDOWS || \
			defined WINDOWS
		#define MFW_BUILD MFW_BUILD_EXECUTABLE_WINDOWS
	#endif
#endif
#ifndef MFW_BUILD
	#define MFW_BUILD MFW_BUILD_EXECUTABLE
#endif