#define MFW_CONFIGURATION_RELEASE 0
#define MFW_CONFIGURATION_DEBUG 1

#define MFW_CONFIGURATION_IS(what) (MFW_CONFIGURATION == MFW_CONFIGURATION_##what)

#if defined _DEBUG || \
	defined DEBUG
	#define MFW_CONFIGURATION MFW_CONFIGURATION_DEBUG
#elif defined _NDEBUG || \
		defined NDEBUG
	#define MFW_CONFIGURATION MFW_CONFIGURATION_RELEASE
#else
	#define MFW_CONFIGURATION MFW_CONFIGURATION_RELEASE
#endif

#ifdef DEBUG
	#undef DEBUG
#endif